name: SocialBridge-TgBridge
version: '0.9.0'
main: io.github.kosyakmakc.SocialBridge.TgBridge.paper.TgBridgeIntegrationPlugin
api-version: '1.21'
authors: [ kosyakmakc ]
folia-supported: true
depend: [SocialBridge, SocialBridge-telegram, AuthSocial, tgbridge] 